### ISSUE TITLE
LSODE

### ISSUE THREAD

**Issue by ChrisRackauckas** [luchr/ODEInterface.jl#1]
LSODE is an old popular stiff solver. [Reference](https://computation.llnl.gov/casc/nsde/pubs/u113855.pdf) and [blog post](http://lh3lh3.users.sourceforge.net/solveode.shtml). Given that it has had quite a long history as one of the ODE solvers, it would be nice to have it available in Julia as well. It seems like it would fit best here given that this seems to be the core library which holds all of the C/Fortran codes.

**Comment by luchr** [comment]
Thank you for the pointers/links. I hope I find the time to take a closer look at the ODEPACK. 
At [ODEPACK's homepage](https://computation.llnl.gov/casc/odepack/odepack_home.html) they say the code is public domain and freely available, but for downloading they need some personal data. If I find the time to write an interface, I hope I get the permission by LLNL to include their source code in this Julia Package.

**Comment by ChrisRackauckas** [comment]
No, [they are available freely](http://www.netlib.org/odepack/) or [they are here](https://people.sc.fsu.edu/~jburkardt/f77_src/odepack/odepack.html). 

BTW, thanks for your work on this package. I have wrapped the functionality of this package into DifferentialEquations.jl [so that these solvers are options](https://github.com/ChrisRackauckas/DifferentialEquations.jl/blob/master/examples/Calling%20External%20Solvers%20-%20ODEjl%20and%20ODEInterface.ipynb).

**Comment by luchr** [comment]
Cool. Thanks for the download-links.
After my holidays, I'll start with the interfaces.

**Comment by rveltz** [comment]
I agree, they are necessary to solve stiff problems [http://lh3lh3.users.sourceforge.net/solveode.shtml](url)

**Comment by ChrisRackauckas** [comment]
Ehh, they aren't necessary for stiff problems. CVODE in [Sundials.jl](https://github.com/JuliaMath/Sundials.jl) will usually do better. This is more so for historical compatibility and algorithm testing. Many codes already used LSODE and to match the results with Julia implementations it would be nice to have a Julia wrapper. But also, it's implementation is quite different than CVODE and so having both wrapped would be good for academic studies between algorithms. 

One this is wrapped along with the other methods in ODEInterface (and thus in DifferentialEquations.jl as well), it will be really easy to test Radau, native Julia stiff solvers from both DifferentialEquaitons.jl and ODE,jl, CVODE, and LSODE all on the same problems with no code modifications necessary (LSODE is actually the only part left to wrap) . It will help us benchmark and understand which parts are crucial for good performance, and hopefully develop even better solvers.

**Comment by rveltz** [comment]
Hum,

I have tried Sundials in Julia and in PETSc, it does not have automatic between stiff and non-stiff methods. Hence, in case where the problem "stiffness" changes, LSODA should perform "better".

**Comment by ChrisRackauckas** [comment]
CVODE automatically switches between Adoms-Moulton methods for non-stiff and BDF methods for stiff. If it isn't doing it, then it's just not wrapped correctly (I just started playing with the Julia wrapper yesterday and there seems like there might be an issue at least with the adaptivity/dense output)

CVODE uses Nystrom-style "accounting" verses the variable coefficient implementation of LSODA. This makes it better for the adaptive timestepping, whereas LSODA has to rely more on order reductions. This for many problems makes it more efficient.

**Comment by ChrisRackauckas** [comment]
Correction, playing with CVODE today. It doesn't automatically switch. My bad, always thought it did. Anyways, I'll probably be implementing that natively anyways. LSODA would be a short term fix.

**Comment by ChrisRackauckas** [comment]
BTW @rveltz, are PETSc's ODE solvers worth wrapping? It seems like what they offer is really basic in that department, but I don't know the library well.

**Comment by rveltz** [comment]
Hi,

I would say no. They 'just' provide a wrapper to sundials'. Take a look at petsc's pdf which is really good, the section on TS is well explained. 

To me, the power of PETSc is more in its nonlinear solvers which are MatrixFree. Once you have you have such nonlinear methods, you can build methods for solving large systems of stiff odes.

**Comment by ChrisRackauckas** [comment]
Okay, that's what I thought. Thanks for explaining it. I always thought PETSc was mostly a nonlinear solver / iterative methods library, but I kept hearing about "PETSc's TS methods". Whenever I looked at it... it just looked like a few simple RK methods and a wrapper to Sundials. Since that seems to be the case, there's no use in testing against those ODE solver implementations (though the other parts are still useful!)

**Comment by rveltz** [comment]
Well, there are some IMEX and DAE solvers that are interesting, not sure they are from PETSc though.

**Comment by rveltz** [comment]
@luchr Did you have the chance to start looking at LSODA?

**Comment by rveltz** [comment]
@luchr Did you have the chance to start looking at LSODA?

**Comment by ChrisRackauckas** [comment]
You might want to look into the thread-safe version of LSODA recently created by @sdwfrost https://github.com/sdwfrost/liblsoda

**Comment by ChrisRackauckas** [comment]
Closing due to https://github.com/rveltz/LSODA.jl . Good job @rveltz !

**Comment by rveltz** [comment]
> On 21 Nov 2016, at 17:38, Christopher Rackauckas notifications@github.com wrote:
> 
> Closing due to https://github.com/rveltz/LSODA.jl https://github.com/rveltz/LSODA.jl . Good job @rveltz https://github.com/rveltz !

Thank you!

Simon Frost helped doing it.

It still needs some edits before it is finished, it should not take us too much time.

Best regards

Romain

**Comment by rveltz** [comment]
> On 21 Nov 2016, at 17:38, Christopher Rackauckas <notifications@github.com <mailto:notifications@github.com>> wrote:
> 
> Closing due to https://github.com/rveltz/LSODA.jl https://github.com/rveltz/LSODA.jl . Good job @rveltz https://github.com/rveltz !

Thank you!

It still needs some edit but it should be quickly done,

Simon Frost also helped!
