### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by zimmermm** [luchr/ODEInterface.jl#17]
Just updated my Julia packages with Pkg.update() and get the following build error:

```
.julia/v0.6/ODEInterface/src/colnew.f:846:34:
      1          W, V, RHS, DUMMY, INTEGS, IPVTG, IPVTW, RNORM, 0,
                                  1
Error: Actual argument contains too few elements for dummy argument ‘integs’ (1/3) at (1)
```

**Comment by luchr** [comment]
Please try the newest commit in the devjulia_v0.4-v0.6 branch that I've checked in a few seconds ago.

The new gcc8 compiler made this a error (instead of a warning).

If this helps, I'll try to get a new version out for julia v0.4-v0.6.

**Comment by zimmermm** [comment]
Works! Thank you for the immediate reply
