### ISSUE TITLE
Windows Build

### ISSUE THREAD

**Issue by ChrisRackauckas** [luchr/ODEInterface.jl#2]
Hey, I can't seem to get the Windows build to work. I installed mingw-w64 and in the terminal when I run `gfortran` it shows that it's in my path. However, when I run `Pkg.build("ODEInterface")` I get an error `LoadError: Currently only gfortran is supported`.

**Comment by luchr** [comment]
For Windows `build.jl` tries a `where gfortran` to find the `gfortran.exe` program. You can skip this method for finding gfortran by setting the environment variable "ODEINTERFACE_GFORTRAN" to the exe-file (including the complete path and the extension) for gfortran to use. If this environment variable is found, then no "where" test is done.
The value may be something like `C:\Program Files\mingw-w64\x86_64.5.2.0-posix-seh-rt_v4-rev0\mingw64\bin\gfortran.exe`.

**Comment by ChrisRackauckas** [comment]
I put in the path and still have issues:

``` julia
julia> ENV["ODEINTERFACE_GFORTRAN"]= "C:\\\"Program Files\"\\mingw-w64\\x86_64-6.1.0-posix-seh-rt_v5-rev0\\mingw64\\bin\\gfortran.exe"
"C:\\\"Program Files\"\\mingw-w64\\x86_64-6.1.0-posix-seh-rt_v5-rev0\\mingw64\\bin\\gfortran.exe"

julia> Pkg.build("ODEInterface")
INFO: Building ODEInterface
WARNING: `@windows` is deprecated, use `@static is_windows()` instead
 in depwarn(::String, ::Symbol) at .\deprecated.jl:64
 in @windows(::Any, ::Any) at .\deprecated.jl:473
 in include_from_node1(::String) at .\loading.jl:426
 in evalfile(::String, ::Array{String,1}) at .\loading.jl:442 (repeats 2 times)
 in cd(::##2#4, ::String) at .\file.jl:48
 in (::##1#3)(::IOStream) at .\none:13
 in open(::##1#3, ::String, ::String) at .\iostream.jl:113
 in eval(::Module, ::Any) at .\boot.jl:234
 in process_options(::Base.JLOptions) at .\client.jl:239
 in _start() at .\client.jl:318
while loading C:\Users\Chris\.julia\v0.5\ODEInterface\deps\build.jl, in expression starting on line 1
========================================================[ ERROR: ODEInterface ]========================================================

LoadError: could not spawn `'C:\"Program Files"\mingw-w64\x86_64-6.1.0-posix-seh-rt_v5-rev0\mingw64\bin\gfortran.exe' -c -fdefault-integer-8 -fdefault-real-8 -fdefault-double-8 -o 'C:\Users\Chris\.julia\v0.5\ODEInterface\src\dopri5.o' 'C:\Users\Chris\.julia\v0.5\ODEInterface\src\dopri5.f'`: no such file or directory (ENOENT)
while loading C:\Users\Chris\.julia\v0.5\ODEInterface\deps\build.jl, in expression starting on line 147

=======================================================================================================================================

===========================================================[ BUILD ERRORS ]============================================================

WARNING: ODEInterface had build errors.

 - packages with build errors remain installed in C:\Users\Chris\.julia\v0.5
 - build the package(s) and all dependencies with `Pkg.build("ODEInterface")`
 - build a single package by running its `deps/build.jl` script

=======================================================================================================================================
```

**Comment by luchr** [comment]
It looks like you have quotes inside your path description (around `Program Files`). Have you tried without the quotes? `build.jl` takes care of the "quoting" (and quotes the complete path). I think that's the reason why the path is not found.

In the new version, I'll take care to use `@windows` for older julia versions and `@static is_windows()` for newer julia versions.

**Comment by ChrisRackauckas** [comment]
I tried it without the quotes first. Same issue

``` julia
julia> ENV["ODEINTERFACE_GFORTRAN"]= "C:\\Program Files\\mingw-w64\\x86_64-6.1.0-posix-seh-rt_v5-rev0\\mingw64\\bin\\gfortran.exe"
"C:\\Program Files\\mingw-w64\\x86_64-6.1.0-posix-seh-rt_v5-rev0\\mingw64\\bin\\gfortran.exe"

julia> Pkg.build("ODEInterface")
INFO: Building ODEInterface
WARNING: `@windows` is deprecated, use `@static is_windows()` instead
 in depwarn(::String, ::Symbol) at .\deprecated.jl:64
 in @windows(::Any, ::Any) at .\deprecated.jl:473
 in include_from_node1(::String) at .\loading.jl:426
 in evalfile(::String, ::Array{String,1}) at .\loading.jl:442 (repeats 2 times)
 in cd(::##2#4, ::String) at .\file.jl:48
 in (::##1#3)(::IOStream) at .\none:13
 in open(::##1#3, ::String, ::String) at .\iostream.jl:113
 in eval(::Module, ::Any) at .\boot.jl:234
 in process_options(::Base.JLOptions) at .\client.jl:239
 in _start() at .\client.jl:318
while loading C:\Users\Chris\.julia\v0.5\ODEInterface\deps\build.jl, in expression starting on line 1
============================[ ERROR: ODEInterface ]=============================

LoadError: failed process: Process(`'C:\Program Files\mingw-w64\x86_64-6.1.0-posix-seh-rt_v5-rev0\mingw64\bin\gfortran.exe' -c -fdefault-integer-8 -fdefault-real-8 -fdefault-double-8 -o 'C:\Users\Chris\.julia\v0.5\ODEInterface\src\dopri5.o' 'C:\Users\Chris\.julia\v0.5\ODEInterface\src\dopri5.f'`, ProcessExited(1)) [1]
while loading C:\Users\Chris\.julia\v0.5\ODEInterface\deps\build.jl, in expression starting on line 147

================================================================================

================================[ BUILD ERRORS ]================================

WARNING: ODEInterface had build errors.

 - packages with build errors remain installed in C:\Users\Chris\.julia\v0.5
 - build the package(s) and all dependencies with `Pkg.build("ODEInterface")`
 - build a single package by running its `deps/build.jl` script

================================================================================
```

**Comment by luchr** [comment]
No. Now it is a _different_ issue. The first one was a not-found issue (ENOENT). In the second case the process terminated with errors.

What is the error if you execute the shown call on the Windows command line, i.e.

```
"C:\Program Files\mingw-w64\x86_64-6.1.0-posix-seh-rt_v5-rev0\mingw64\bin\gfortran.exe" -c -fdefault-integer-8 -fdefault-real-8 -fdefault-double-8 -o "C:\Users\Chris\.julia\v0.5\ODEInterface\src\dopri5.o" "C:\Users\Chris\.julia\v0.5\ODEInterface\src\dopri5.f"
```

**Comment by ChrisRackauckas** [comment]
Oh my bad, didn't notice the difference. When I run that command I have a f951.exe application error. 

> The application was unable to start correctly (0xc000007b).

Following [this StackExchange post](http://stackoverflow.com/questions/25124182/mingw-gcc-the-application-was-unable-to-start-correctly-0xc000007b), I removed the mingw-64 folder from the environment variables. Still the same error. Then I used

> C:\WINDOWS\system32>where libquadmath-0.dll
> C:\Users\Chris\AppData\Local\Julia-0.5.0-rc0\bin\libquadmath-0.dll

So I looks like having Julia in the environment variables (for Juno) was messing with it. So I go rid of the Julia environment variables, but I still get the same error.

**Comment by luchr** [comment]
Having a different mingw version than Julia and then having Julia in the path before mingw is problematic.
Have you tried it with only the mingw-w64 folder (to be more specific the `...\mingw64\bin` folder) in the path?

**Comment by ChrisRackauckas** [comment]
Looks like that got closer:

``` julia

"C:\\Program Files\\mingw-w64\\x86_64-6.1.0-posix-seh-rt_v5-rev0\\mingw64\\bin\\gfortran.exe"
INFO: Building ODEInterface
============================[ ERROR: ODEInterface ]=============================

LoadError: failed process: Process(`'C:\Program Files\mingw-w64\x86_64-6.1.0-posix-seh-rt_v5-rev0\mingw64\bin\gfortran.exe' -c -fdefault-integer-8 -fdefault-real-8 -fdefault-double-8 -o 'C:\Users\Chris\.julia\v0.5\ODEInterface\src\dopri5.o' 'C:\Users\Chris\.julia\v0.5\ODEInterface\src\dopri5.f'`, ProcessExited(1)) [1]
while loading C:\Users\Chris\.julia\v0.5\ODEInterface\deps\build.jl, in expression starting on line 166

================================================================================

================================[ BUILD ERRORS ]================================

WARNING: ODEInterface had build errors.

 - packages with build errors remain installed in C:\Users\Chris\.julia\v0.5
 - build the package(s) and all dependencies with `Pkg.build("ODEInterface")`
 - build a single package by running its `deps/build.jl` script

================================================================================
```

**Comment by ChrisRackauckas** [comment]
BTW:

``` julia
versioninfo()

Julia Version 0.5.0-rc0+46
Commit 905e2bd (2016-07-29 01:13 UTC)
Platform Info:
  System: NT (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-4770K CPU @ 3.50GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, haswell)
```

and I'm on master.

**Comment by luchr** [comment]
Why "got closer"? Same line (first compilation) that makes problems. Again: What is (now) the error message for the given gfortran call? If the mingw-compiler does not work (from the command line) then the building of the package will fail.

I've installed Windows 7 Enterprise SP 1, and the same MinGW-W64 6.1.0 x86_64 posix-seh compiler you are using. I appended the mingw-bin folder to the system path and I have no problems building the package.

**Comment by ChrisRackauckas** [comment]
I get the same

> The application was unable to start correctly (0xc000007b).

as before. This is Windows 10 anniversary update. I re-installed mingw-w64 and get the same issue, both on the normal command prompt and the administrator one.

**Comment by luchr** [comment]
OK. This has nothing to do with this ODEInterface package, but is a installation problem with mingw. I don't know windows 10. Here are my ideas:

To rule out a PATH problem try the following (in a non-Admin command console):

```
set PATH=
cd "C:\Program Files\mingw-w64\x86_64-5.2.0-posix-seh-rt_v4-rev0\mingw64\bin\"
gfortran.exe -c -o C:\Users\Chris\test.dat  C:\Users\Chris\.julia\v0.5\ODEInterface\src\dopri5.f
```

Does this produce an/the error or does this create a `test.dat` in your home directory?

If you get the same error, try running [a Process Monitor](https://technet.microsoft.com/en-us/sysinternals/bb896645) to see, what your mingw-installation tries to load and what file causes the error message.

**Comment by ChrisRackauckas** [comment]
+500. It was a path issue. So I went one by one to find the offender. It was that Atom had added itself to my path when I installed Juno. You might want to add a note to the README.

Thanks for helping me out with this! I'm not very familiar with these tools on Windows... I've always just retreated to Linux the first time of having any of these problems.
