### ISSUE TITLE
Using ODEInterface in Juliabox(.com)

### ISSUE THREAD

**Issue by luchr** [luchr/ODEInterface.jl#21]
If you get the error
```
Error: Error building `ODEInterface`: 
[ Info: Using JuliaBox Pkg Manager
ERROR: LoadError: ArgumentError: Package REPL not found in current path:
- Run `import Pkg; Pkg.add("REPL")` to install the REPL package.
```
simply start a terminal `New -> Terminal` and type the following line:
```
julia -e 'using Pkg; Pkg.add("ODEInterface");Pkg.build("ODEInterface");'
```
This should download, install and build the package successfully.

After this you can use it in notebooks.

**Comment by luchr** [comment]
I leave this open for persons who have this problem.

**Comment by ViralBShah** [comment]
Can close this one. Since JuliaBox is no longer around.

**Comment by luchr** [comment]
OK.
