### ISSUE TITLE
loadODESolvers() not working

### ISSUE THREAD

**Issue by NirvikNU** [luchr/ODEInterface.jl#24]
I am using Windows 10 64 bit.
I performed the following steps in Juno in Julia REPL:
] add ODEInterface
build ODEInterface
loadODESolvers()

The ODEInterface package is added and built as normal however the loadODESolver() command throws an “UndefVarError”.
I have installed and added mingw64 to my path so cannot understand what is going wrong. And I cannot use any of the ODEInterface functions like radau in my code. Please help.
Thanks

**Comment by luchr** [comment]
Can you give me the location (line number and/or a stacktrace) where the `UndefVarError` was thrown?

Please also have a look at #18  and my solution hint https://github.com/luchr/ODEInterface.jl/issues/18#issuecomment-469067584 .

I've tested ODEInterface for different Windows versions, see [appveyor results](https://ci.appveyor.com/project/luchr/odeinterface-jl/branch/master).

**Comment by NirvikNU** [comment]
The Stacktrace :
[1] top-level scope at REPL[33]:1

I am using mingw-64 and Julia 64.

**Comment by NirvikNU** [comment]
I tried the same steps in Ubuntu OS and get exactly the same error when calling loadODESolver(). I think I am doing something fundamentally wrong. Here is a screenshot.
![Screenshot from 2019-10-11 20-48-03](https://user-images.githubusercontent.com/56455477/66693200-108fe680-ec6c-11e9-9785-da6804f92eff.png)

**Comment by luchr** [comment]
Ah. Oh. Yes. The Stacktace helps a lot. It is:

```julia
using ODEInterface; ODEInterface.loadODESolvers()
```

or

```julia
using ODEInterface; @ODEInterface.import_huge; loadODESolvers()
```

By default ODEInterface does no namespace pollution and does not import names like `loadODESolvers`. There are two macros `import_huge` and `import_normal` to import a huge set of symbols or a "normal" set of symbols.

**Comment by NirvikNU** [comment]
Thanks for clarifying. That works fine now.
But I can't still use the solvers in ODEInterfaceDiffEq.jl in my code:
![Screenshot from 2019-10-13 19-27-38](https://user-images.githubusercontent.com/56455477/66724893-faf7f980-edf0-11e9-8f12-3d4e66d09547.png)

**Comment by NirvikNU** [comment]
Update: turns out that I had accidentally installed the 32-bit version of Julia in my 64-bit system...got the proper version now everything is working fine! Thanks a lot for all the help.

I am using this package to access the high accuracy radau solver for use in my Hodgkin Huxley neuron model...earlier I was using MATLAB's ode15s and it is interesting to find that radau() is giving quite different results. 
Thanks a lot for the help again.
