### ISSUE TITLE
ODEX-P

### ISSUE THREAD

**Issue by ChrisRackauckas** [luchr/ODEInterface.jl#3]
It would be cool to have the parallel extrapolation implementation from [this paper](https://arxiv.org/pdf/1305.6165.pdf), denoted as ODEX-P, in this library. It just takes a simple modification of the ODEX code (see page 19).

**Comment by luchr** [comment]
It takes more than a simple modification to build a robust/tuned parallel extrapolation method. Section 6 in the paper starts with this statement: 

> Development and testing of a tuned parallel extrapolation [...] code is beyond the scope of this paper.

They used ODEX to provide a "simple example" showing that speedups are possible with parallelization. For this simple tests they even disabled the adaptive order selection. That is one of the features of an extrapolation method that one does not want to turn off.

I don't want to include such a first-shot-example. When/if there will be a heavily tested production version, I'll take a look again.

**Comment by ChrisRackauckas** [comment]
Got it.
