### ISSUE TITLE
AppVoyer Compatibility?

### ISSUE THREAD

**Issue by ChrisRackauckas** [luchr/ODEInterface.jl#4]
It seems ODEInterface is should work on Windows. Is there any way for it to build on AppVoyer? Right now I have tests which use ODEInterface disabled on AppVoyer since it needs to find a mingw-64 install.

**Comment by luchr** [comment]
According to the [documentation of the software installed for building](https://www.appveyor.com/docs/installed-software#mingw-msys-cygwin) they have even mingw-w64 installed. After extending the path, compilation should be possible.
[Also check the license of bvpsol before deploying.]

But I don't understand the concept/goal: Do you want to build julia-packages inside AppVoyer and then (re-)package them and deploy them? For the ODEInterface this means you have to deploy all the mingw-w64 libraries, too. At least the one, it depends on.

**Comment by ChrisRackauckas** [comment]
Not for deployment, just for Windows CI testing.

**Comment by ChrisRackauckas** [comment]
I tried messing with the path in the same way as the other issue but was getting the same error. I'm giving up on it for now since ODEInterface builds fine on Travis CI anyways.
