### ISSUE TITLE
In-place functions

### ISSUE THREAD

**Issue by ChrisRackauckas** [luchr/ODEInterface.jl#5]
Is there any way to use in-place functions with the wrapped codes, i.e. `f(du,u,u)`? Or do they not support that? I found my implementations in DifferentialEquations.jl were able to dominate the dopri5 code, and I think this may be one of the reasons.

**Comment by luchr** [comment]
I'm not sure what you mean with "in-place functions".
(a) Functions where the memory for the result (the derivatives) is pre-allocated
(b) ODE's where you cannot solve for `du=u'` and `u'` appears implictly
(c) something completely different

for (a): this is supported
for (b): most of the solvers expect to have `u'` explicitly on the left hand side (sometimes a so-called mass-matrix is supported)
for (c): please explain

**Comment by ChrisRackauckas** [comment]
Oh I see. I found the part of the documentation for it (version (a)). I can't seem to get this function to work:

```julia
  function f(du,u,t)
    @inbounds for i in eachindex(u)
      du[i] = α[i]*u[i]
    end
    du
  end
```

**Comment by ChrisRackauckas** [comment]
I found it in the docs. From the way the README was written I thought it didn't exist.

**Comment by luchr** [comment]
For (a): see ODEInterface.help_callsolvers
mind the order of the arguments: `t  x  dx`.

**Comment by ChrisRackauckas** [comment]
Yeah, the order of the arguments is why I didn't think it exists. But a swap made it work.

**Comment by ChrisRackauckas** [comment]
How exactly are you setting `RHS_CALL_INSITU`? The following function is still thought to be not in-place in ODEInterface, and so it errors at `result=cbi.rhs(t,x)` since `RHS_CALL_RETURNS_ARRAY` is true:

```julia
    if !isinplace && typeof(u)<:AbstractArray
      f! = (u,t,du) -> (du[:] = vec(prob.f(reshape(u,sizeu),t)); nothing)
    else
      f! = (u,t,du) -> (vec(prob.f(reshape(du,sizeu),reshape(u,sizeu),t)); nothing)
    end
```

Is it looking for number of arguments? Return type?
