### ISSUE TITLE
Migrate to JuliaDiffEq?

### ISSUE THREAD

**Issue by ChrisRackauckas** [luchr/ODEInterface.jl#7]
We are trying to have one organization to coordinate APIs for the differential equations packages in Julia. I think ODEInterface would be a good fit in this organization. I think this package would be a good place to wrap the other popular Fortran solvers (ROCK, LSODE, etc.) and coordinate those efforts along with other solvers.

**Comment by luchr** [comment]
There are two parts in this issue:
1. Part: odepack (see other issue)
   Yes, I definitively want to wrap other Fortran solvers. In that moment when I've time I'll start with odepack.
2. Part: coordination of an API
   In my view, that's a really really interesting part. 

First my opinion about the current API of the ODEInterface: "bad" 😞
Why? Neither does it make use of julia's powerful function dispatching nor does it expose the underlying (mathematical) structures/connections. At the moment it is just a dictionary of String-Value pairs. That's ugly. One can try to order them in the documentation, but that's an attempt to fight the symptoms, but not the cause.

If there are other ideas to structure the solver-options (there can be many) with the help of OO-mechanisms and in an extendable way, then I'll keen to hear them and/or put my two cents to it.

But I've no idea how such an "organization to coordinate APIs" might look like ...

**Comment by ChrisRackauckas** [comment]
That's what we're doing here: https://github.com/JuliaDiffEq

Of course, it's more essential for PDE solvers / components of PDE solvers to play nicely together. ODE solvers are much more simpler, but I think pooling them together will have other advantages. There is a unified Gitter chatroom for JuliaDiffEq as well which will make it easier to give/get help. We've already pooled together Sundials.jl and ODE.jl there, and DifferentialEquations.jl will follow soon.

**Comment by ChrisRackauckas** [comment]
I think that our current setup is fine. ODEInterfaceDiffEq provides bindings to this packages to the common API in a way that doesn't introduce any dependencies here, and the API can grow/expand as needed. It's not included by default with DifferentialEquations because the requirement of being able to compile FORTRAN is too large, and so there's no major compatibility concerns and problems with the link can just be dealt with when they come up. 

As for remaining methods, I think we are doing really well now. With LSODA.jl, DASKR.jl, and Sundials.jl, along with the native implementation DASSL.jl (which admittedly isn't very optimized right now, but I'll take a pass at it later this year), I don't see a need for odepack. Your software then covers a lot of other problem domains. I think the only solver types which are remaining are those from https://github.com/luchr/ODEInterface.jl/issues/6 . RETARD is no longer necessary since the DelayDiffEq.jl methods are benchmarking really well. There's also a lot of work being done on native geometric integrators. However, I don't see anyone offering ROCK methods or something like RADAR5 anytime soon, so those would be the big contributions to the ecosystem which are left. So we can continue this in the other issue. 

Thanks for all of your hard work! Your package has been really essential for the development and testing of the native Julia methods. I am a mathematician with little prior FORTRAN experience (if you couldn't already tell...) and this has made it extremely easy for me to be able to use these methods as a test suite.
