### ISSUE TITLE
Tests failing on MacOSX?

### ISSUE THREAD

**Issue by ChrisRackauckas** [luchr/ODEInterface.jl#8]
Sometime within the last week my MacOSX tests started failing due to this dependency, with an error during building:

``` julia
INFO: Building ODEInterface
============================[ ERROR: ODEInterface ]=============================
LoadError: Currently only gfortran is supported.
while loading /Users/travis/.julia/v0.5/ODEInterface/deps/build.jl, in expression starting on line 157
================================================================================
```

The Travis script I am using is similar to yours, adding in there:

``` julia
addons:
  apt:
    packages:
      - gfortran
```

for gfortran, which seems to no longer apply on MacOSX. This makes me think something changed on MacOSX Travis to change this. Do you mind re-running your tests to see if this is the case?

**Comment by luchr** [comment]
I changed the `.travis.yml` file accordingly in the branches 'devel' and 'master'.

This change will be included in the next version of the ODEInterface package. [Because no julia code has changed, there is no need to make a new version only because of the this Travis change.]

**Comment by ChrisRackauckas** [comment]
Thanks
